apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cert-watcher
  template:
    metadata:
      labels:
        app: cert-watcher
    spec:
      containers:
      - name: cert-watcher
        image: cert-watcher:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000